apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nicolajskov/fortune-frontend
        ports:
          - containerPort: 8080
        env:
          - name: BACKEND_DNS
            value: backend-svc
status: {}
