apiVersion: v1
kind: Service
metadata:
  labels:
    run: backend
  name: backend
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    run: backend
  type: ClusterIP