apiVersion: app/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-backend
  name: deployment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-backend
    spec:
      containers:
      - image: nanies20/simple-fortune-cookie-backend:latest
        name: backend
        resources: {}
status: {}
