# Build
FROM golang:1.19-alpine as builder
COPY . /src/
ENV CGO_ENABLED=0
ENV GOOS=linux
WORKDIR /src/backend
RUN go mod tidy && \
    go build -o backend

# Run
FROM scratch
COPY --from=builder /src/backend/backend /
ENTRYPOINT ["/backend"]
