# Build
FROM golang:1.19-alpine as builder
ADD . /src/
RUN cd /src/frontend && go build -o frontend

# Run
FROM alpine:3.16
COPY --from=builder /src/frontend/frontend /app/
ADD ./frontend /app/
WORKDIR /app
ENTRYPOINT ["./frontend"]
