# Build
FROM golang:1.19-alpine as builder
ADD . /src/
RUN cd /src/backend && go build -o backend

# Run
FROM alpine:3.16
COPY --from=builder /src/backend/backend /app/
WORKDIR /app
ENTRYPOINT ["./backend"]
