# Build
FROM golang:1.13.2 as builder
ADD . /src/
RUN cd /src/frontend && go build -o frontend

# Run
FROM ubuntu:22.04
COPY --from=builder /src/frontend/frontend /app/
ADD ./frontend /app/
WORKDIR /app
ENTRYPOINT ["./frontend"]
