apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fortune
  name: fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fortune
    spec:
      containers:
      - name: redisDB
        image: redis
        resources: {}
      - name: backend
        depends-on: redisDB 
      - name: frontend
        depends-on: backend
status: {}
