apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-backend
  name: service-backend
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: deployment-backend
  type: NodePort
status: 
  loadbalancer: {}