apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-db
  name: service-db
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deployment-db
  type: NodePort
status: 
  loadbalancer: {}