apiVersion: v1
kind: Service
metadata: 
  name: backend-service
  labels:
    app: backend-deployment
spec:
  type: NodePort
  selector:
    app: backend-deployment
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

