FROM golang:latest AS compiler

WORKDIR /go/src/app

COPY . .

RUN go mod download github.com/gomodule/redigo && go build

CMD ["./backend"]

#backend dockerfile
#FROM ubuntu:latest

#start the backend
#CMD ["go", "run", "/backend"]