FROM golang:1.16 AS builder
WORKDIR /src
COPY . /src
RUN go get -d -v && CGO_ENABLED=0 GOOS=linux go build backend

# final stage
FROM scratch
COPY --from=builder /src/backend /src/backend
ENTRYPOINT ["/src/backend"]