FROM golang:1.16 AS builder
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download 
COPY *.go ./
RUN go build -o /app

FROM ubuntu:latest AS main
COPY --from=builder /app /myapp
EXPOSE 6379
ENTRYPOINT ["/myapp/app"]