apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mizzlethehorse/frotend:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mizzlethehorse/backend:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: ClusterIP
---