apiVersion: v1
kind: Service
metadata:
  name: sfc-backend-service
spec:
  selector:
    app: sfc-backend
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP 