apiVersion: v1
kind: Service
metadata:
  name: sfc-frontend-service
spec:
  selector:
    app: sfc-frontend
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080 
  type: NodePort  