apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfc-redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
      - name: redis-data-volume
        persistentVolumeClaim:
          claimName: pvc-redis
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379   
        volumeMounts:
        - mountPath: "/redis-master-data"
          name: redis-data-volume