#Build file for dev CI pipeline
name: Simple fortune pipeline
on:
  push:
    branches:
      - "dev/**"
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GET_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    name: Clone repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: simple-fortune-code
          path: .
  Build-and-Test:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: simple-fortune-code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'    
      - name: Build backend
        run: cd backend && go build .
      - name: Build frontend
        run: cd frontend && go build .  
      - name: Test with GO
        run: cd frontend && go test 
      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: simple-fortune-code
          path: .

