name: Go
on:
  push:
    branches:
      - development

env:
  docker_username: ${{ secrets.UNAME }}
  docker_password: ${{ secrets.PASS }}

jobs:

  Build:
    needs: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update  && sudo apt-get install golang-go -y
      - name: Build
        run: cd frontend && go build .
      - name: Build
        run: cd backend && go build .

  Test:
    runs-on: self-hosted
    steps:
      - name: Test
        run: cd frontend && go test .

  Push_to_docker:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username}}
          password: ${{ env.docker_password}}
      - name: Build and push Docker back
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./backend
          push: true
          tags: nicobah/devops_backend
      - name: Build and push Docker front
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./frontend
          push: true
          tags: nicobah/devops_frontend

  Test_kubernetes:
    needs: Push_to_docker
    runs-on: self-hosted
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: setup cluster
        run: chmod +x ./kubernetes/td.sh && bash ./kubernetes/td.sh
      - name: test cluster
        run: chmod +x ./kubernetes/test.sh && bash ./kubernetes/test.sh
