name: Java_CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
jobs:







  test:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
    - name: Download code
      uses: actions/download-artifact@v1
      with:
        name: code
        path: .
    - name: Execute go test
      run: chmod +x frontend/main_test.go && frontend/main_test.go.sh