name: CICD
on:
  push:
    branches:
    - "main"
    - "dev**"
    - "self-hosted"
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build
      run: cd frontend/ && go build  
    - name: Run testing
      run: cd frontend/ && go test
    