name: Go CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload Repo
        uses: actions/upload-artifact@v1
        with:
          name: code
          path: .

  Frontend-test:
    runs-on: ubuntu:latest
    needs: [Clone-down]
    steps:
    - name: Download code
      uses: actions/download-artifact@v1
      with:
        name: code
        path: .
    - name: Execute go test
      steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
  - run: go test
      run: chmod +x frontend/main_test.go && frontend/main_test.go
      
