name: hello-world-1
on:
  push:
    branches:
      - "automation"
      - "cd"
      - "main"
  pull_request:
    branches:
      - "automation"
      - "cd"
      - "main"
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: frontend-test
        run: go build -v frontend/main_test.go