name: hello-world
on:
  push:
    branches:
      - "automation"
      - "cd"
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: frontend-test
        run: go build -v frontend/main_test.go