env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}

name: SmokeTests
on:
  workflow_run:
    workflows: ["container-reg"]
    types: 
      - completed
jobs:
  docker-test:
    name: build docker images and curl 8080
    runs-on: ubuntu-latest
    steps:
      - name: docker-run
        run: docker-compose up -d
      - name: test
        run: curl -s 172.17.0.1:8080 | grep "Fortune cookie application"
      - name: docker-stop
        run: docker-compose down
