name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
      - name: Install dependencies
        run: apt-get update && apt-get install golang-go && go mod download github.com/gomodule/redigo
      - name: Build
        run: go build /frontend
      - name: Test
        run: go test /frontend
