name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update  && sudo apt-get install golang-go -y
      - name: Build
        run: cd frontend && go build .
      - name: Test
        run: cd frontend && go test .
  Push_to_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: set up qemu
        uses: docker/setup-qemu-action@v2
      - name: set up build action
        uses: docker/setup-buildx-action@v2
      - name: Log in to docker
        uses: docker/login-action@v2
        with:
          username: ${{ USERNAME }}
          password: ${{ PASSWORD }}
        name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
