name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update  && sudo apt-get install golang-go -y
      - name: Build
        run: go build /frontend
      - name: Test
        run: go test /frontend
