name: Tests
on: [push, pull_request]
jobs:
  go-tests:
    name: Run go tests
    runs-on: ubuntu-latest
    container: golang:1.17
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: go test ./...
