name: ci

on:
  push:
    branches:
      - 'Nadia'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ../simple-fortune-cookie/backend
          push: true
          tags: user/app:latest
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ../simple-fortune-cookie/frontend
          push: true
          tags: user/app:latest
  

  