name: workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: build application
        run: chmod +x ci/build-backend.sh && ci/build-frontend.sh
      - name: test-step
        run: go test backend && frontend